feature: Add SDK support for SparkML Serving Container version 2.4
aws/sagemaker-python-sdk pull request #1917
Opened 2020-09-22 19:45 UTC by mahithsuresh

*Issue #, if available:*

*Adding SDK support for SparkML Serving Container version 2.4*

*Modified and verified unit tests and integration tests that they ran successfully*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-22 23:42 UTC, ChuyangDeng commented
Hi @mahithsuresh, thanks for the contribution! Could you also update the `image_uris` config for spark-ml-serving? I already have a PR to update it but I think it's more appropriate to have it here: https://github.com/aws/sagemaker-python-sdk/blob/d6d1012ceb619fac4799d4c10f686567e0d1cb65/src/sagemaker/image_uri_config/sparkml-serving.json (I will close my PR #1904 )

2020-09-22 23:43 UTC, ChuyangDeng requested changes
image_uri update (see above)

2020-09-23 02:49 UTC, mahithsuresh commented
Sure - I have updated the `image_uri` config.

2020-09-23 23:32 UTC, ChuyangDeng approved these changes

2020-09-25 21:54 UTC, merged