throttle list methods
aws/sagemaker-python-sdk pull request #2071
Opened 2021-01-06 18:43 UTC by yzhu0

Add throttle to list methods
https://sim.amazon.com/issues/AML-93631

2021-01-07 18:09 UTC, icywang86rui commented
I am not sure this is the correct way to fix throttling problems. This will add 1 second delay in all the ListApi calls wherever this is used. This might break our customers that has a higher rate for their specific account.

2021-01-07 18:58 UTC, icywang86rui requested changes
Not sure this change is the right fix.

2021-01-08 18:33 UTC, jerrypeng7773 submitted a review, later dismissed

2021-01-15 19:25 UTC, danabens commented
fix unit tests
`[Container] 2021/01/06 18:45:23 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: tox -e flake8,pylint,docstyle,black-check,twine --parallel all. Reason: exit status 1`

2021-01-20 17:45 UTC, yzhu0 commented
> I am not sure this is the correct way to fix throttling problems. This will add 1 second delay in all the ListApi calls wherever this is used. This might break our customers that has a higher rate for their specific account.

since we have rate =2 under ListApi call. We should let it sleep for 1s to prevent API throttling
https://tiny.amazon.com/xh7mx9uw/IronmanUtilizationService/342d6fd1/default-rules.json#L225

2021-01-21 16:39 UTC, danabens approved these changes

2021-01-21 16:45 UTC, danabens reviewed
Rui's comments are correct - should normally list at full speed, once there is a throttling exception list at a slower rate.

2021-01-22 05:44 UTC, yzhu0 commented
> Rui's comments are correct - should normally list at full speed, once there is a throttling exception list at a slower rate.

I update the pr to sleep only when the method is throttled

2021-01-22 17:16 UTC, danabens commented
confirm tested end to end either via integ test or manually

2021-03-03 23:28 UTC, ChoiByungWook requested changes

2021-03-03 23:28 UTC, ChoiByungWook commented on src/sagemaker/apiutils/_base_types.py
> +                        raise error
Can we update unit tests to exercise this line?

2021-03-03 23:32 UTC, ChoiByungWook reviewed
Would it be better to configure the retry strategy in the boto client instead of sleeping?

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html

2021-03-26 17:26 UTC, icywang86rui commented
There has not been any actions for a few weeks. Closing for now. Feel free to reopen.

2021-03-26 17:26 UTC, closed without merging