feature: add inference_id to predict
aws/sagemaker-python-sdk pull request #2093
Opened 2021-01-16 22:07 UTC by akionakamura

*Issue https://github.com/aws/sagemaker-python-sdk/issues/2086:*

*Description of changes:*
Adding `inference_id` to the `Predictor::predict` method, which will be sent to the `invoke_endpoint`. If you provide an `inference_id` value, it is added to the captured data when you enable data capture on the endpoint.

*Testing done:*
Added the test `test_predict_call_with_inference_id` which ensures the `InferenceId` argument is sent to the `boto3` client as per their documentation: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker-runtime.html#SageMakerRuntime.Client.invoke_endpoint

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Hey folks, my first time contributing here. Please let me know if I'm missing something.

2021-01-19 19:48 UTC, metrizable requested changes
Would you please add an integration test with this argument?

2021-01-20 22:50 UTC, akionakamura commented
Hey @metrizable, sure I'll give it a try! I'm struggling to setup integration tests locally, with things like `botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied`. I've looked at https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#run-the-integration-tests, but didn't find anything helpful.

Do you have a documentation, or something, to share on how should I setup for integration tests?

2021-01-26 03:03 UTC, akionakamura commented
For the record, just made the setup with the `SageMakerRole` role in my AWS account, and ran the added integration test:
`export IGNORE_COVERAGE=- ; tox -e py36 -- -s -vv tests/integ/test_predict_with_inference_id.py ; unset IGNORE_COVERAGE`

It was successful:
```
 (inference-id)$ export IGNORE_COVERAGE=- ; tox -e py36 -- -s -vv tests/integ/test_predict_
with_inference_id.py ; unset IGNORE_COVERAGE
GLOB sdist-make: /home/akio/Akio/sagemaker-python-sdk/setup.py
py36 inst-nodeps: /home/akio/Akio/sagemaker-python-sdk/.tox/.tmp/package/1/sagemaker-2.23.6.dev0.zip
py36 installed: alembic==1.4.3,apache-airflow==1.10.11,apipkg==1.5,apispec==1.3.3,appdirs==1.4.4,argcomplete==1.12.2,attrs==19.3.0,awslogs==0.14.0,Babel==2.9.0,bcrypt==3.2.0,black==20.8b1,boto3==1.16.56,botocore==1.19.56,cached-property==1.5.2,cattrs==1.0.0,certifi==2020.12.5,cffi==1.14.4,chardet==4.0.0,click==7.1.2,colorama==0.4.4,colorlog==4.0.2,configparser==3.5.3,contextlib2==0.6.0.post1,coverage==5.3.1,croniter==0.3.37,cryptography==3.3.1,dataclasses==0.8,defusedxml==0.6.0,dill==0.3.3,distlib==0.3.1,distro==1.5.0,dnspython==2.1.0,docker==4.4.1,docker-compose==1.27.4,dockerpty==0.4.1,docopt==0.6.2,docutils==0.16,email-validator==1.1.2,execnet==1.7.1,fabric==2.5.0,filelock==3.0.12,flake8==3.8.4,Flask==1.1.2,Flask-Admin==1.5.4,Flask-AppBuilder==2.3.4,Flask-Babel==1.0.0,Flask-Caching==1.3.3,Flask-JWT-Extended==3.25.0,Flask-Login==0.4.1,Flask-OpenID==1.2.5,Flask-SQLAlchemy==2.4.4,flask-swagger==0.2.13,Flask-WTF==0.14.3,funcsigs==1.0.2,future==0.18.2,google-pasta==0.2.0,graphviz==0.16,gunicorn==19.10.0,idna==2.10,importlib-metadata==3.4.0,importlib-resources==5.0.0,iniconfig==1.1.1,invoke==1.5.0,iso8601==0.1.13,itsdangerous==1.1.0,Jinja2==2.10.3,jmespath==0.10.0,json-merge-patch==0.2,jsonschema==3.2.0,lazy-object-proxy==1.5.2,lockfile==0.12.2,Mako==1.1.4,Markdown==2.6.11,MarkupSafe==1.1.1,marshmallow==2.21.0,marshmallow-enum==1.5.1,marshmallow-sqlalchemy==0.23.1,mccabe==0.6.1,mock==4.0.3,more-itertools==8.6.0,mypy-extensions==0.4.3,natsort==7.1.0,numpy==1.19.5,packaging==20.8,pandas==1.1.5,paramiko==2.7.2,pathspec==0.8.1,pendulum==1.4.4,pluggy==0.13.1,prison==0.1.3,protobuf==3.14.0,protobuf3-to-dict==0.1.5,psutil==5.8.0,py==1.10.0,pycodestyle==2.6.0,pycparser==2.20,pyflakes==2.2.0,Pygments==2.7.4,PyJWT==1.7.1,PyNaCl==1.4.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.0.2,pytest-cov==2.10.1,pytest-forked==1.3.0,pytest-rerunfailures==9.1.1,pytest-xdist==2.2.0,python-daemon==2.2.4,python-dateutil==2.8.1,python-dotenv==0.15.0,python-editor==1.0.4,python-nvd3==0.15.0,python-slugify==4.0.1,python3-openid==3.2.0,pytz==2020.5,pytzdata==2020.1,PyYAML==5.3.1,regex==2020.11.13,requests==2.25.1,s3transfer==0.3.4,sagemaker @ file:///home/akio/Akio/sagemaker-python-sdk/.tox/.tmp/package/1/sagemaker-2.23.6.dev0.zip,sagemaker-experiments==0.1.25,scipy==1.5.4,setproctitle==1.2.1,six==1.15.0,smdebug-rulesconfig==1.0.1,SQLAlchemy==1.3.22,SQLAlchemy-JSONField==0.9.0,SQLAlchemy-Utils==0.36.8,stopit==1.1.2,tabulate==0.8.7,tenacity==4.12.0,termcolor==1.1.0,text-unidecode==1.3,texttable==1.6.3,thrift==0.13.0,toml==0.10.2,tox==3.21.1,typed-ast==1.4.2,typing==3.7.4.3,typing-extensions==3.7.4.3,tzlocal==1.5.1,unicodecsv==0.14.1,urllib3==1.26.2,virtualenv==20.3.1,websocket-client==0.57.0,Werkzeug==0.16.1,WTForms==2.3.3,zipp==3.4.0,zope.deprecation==4.4.0
py36 run-test-pre: PYTHONHASHSEED='3274652685'
py36 run-test: commands[0] | pytest --cov=sagemaker --cov-append -s -vv tests/integ/test_predict_with_inference_id.py
============================================================ test session starts ============================================================
platform linux -- Python 3.6.9, pytest-6.0.2, py-1.10.0, pluggy-0.13.1 -- /home/akio/Akio/sagemaker-python-sdk/.tox/py36/bin/python
cachedir: .tox/py36/.pytest_cache
rootdir: /home/akio/Akio/sagemaker-python-sdk, configfile: tox.ini
plugins: xdist-2.2.0, cov-2.10.1, forked-1.3.0, rerunfailures-9.1.1
collected 2 items

tests/integ/test_predict_with_inference_id.py::test_predict_with_inference_id ------------!PASSED
tests/integ/test_predict_with_inference_id.py::test_invoke_endpoint_with_inference_id PASSEDNo monitors found for endpoint. endpoint: model-inference-id-integ-1611629711-76bb
Arguments: serve
[2021-01-26 02:59:22 +0000] [1] [INFO] Starting gunicorn 19.7.1
[2021-01-26 02:59:22 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-01-26 02:59:22 +0000] [1] [INFO] Using worker: gevent
[2021-01-26 02:59:22 +0000] [41] [INFO] Booting worker with pid: 41
[2021-01-26:02:59:22:INFO] Model loaded successfully for worker : 41
[2021-01-26 02:59:22 +0000] [42] [INFO] Booting worker with pid: 42
[2021-01-26:02:59:22:INFO] Model loaded successfully for worker : 42
[2021-01-26 02:59:22 +0000] [43] [INFO] Booting worker with pid: 43
[2021-01-26 02:59:22 +0000] [44] [INFO] Booting worker with pid: 44
[2021-01-26:02:59:22:INFO] Model loaded successfully for worker : 43
[2021-01-26:02:59:22:INFO] Model loaded successfully for worker : 44


----------- coverage: platform linux, python 3.6.9-final-0 -----------
Name                                                                                                  Stmts   Miss  Cover
-------------------------------------------------------------------------------------------------------------------------
.tox/py36/lib/python3.6/site-packages/sagemaker/__init__.py                                              31      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/_studio.py                                               45      4    91%
.tox/py36/lib/python3.6/site-packages/sagemaker/algorithm.py                                            159     15    91%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/__init__.py                                        0      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/amazon_estimator.py                              141     15    89%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/common.py                                        147      9    94%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/factorization_machines.py                         74      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/hyperparameter.py                                 38      1    97%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/ipinsights.py                                     50      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/kmeans.py                                         52      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/knn.py                                            48      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/lda.py                                            42      1    98%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/linear_learner.py                                126      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/ntm.py                                            54      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/object2vec.py                                    101      1    99%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/pca.py                                            48      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/randomcutforest.py                                40      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/record_pb2.py                                     80      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/amazon/validation.py                                     26      3    88%
.tox/py36/lib/python3.6/site-packages/sagemaker/analytics.py                                            298     20    93%
.tox/py36/lib/python3.6/site-packages/sagemaker/apiutils/__init__.py                                      1      0   100%
.tox/py36/lib/python3.6/site-packages/sagemaker/apiutils/_base_types.py                                 102     [...]

2021-02-09 02:34 UTC, akionakamura commented
Hey @metrizable do you think this still makes sense?

2021-02-25 04:48 UTC, ChoiByungWook approved these changes

2021-02-25 04:48 UTC, ChoiByungWook commented on src/sagemaker/local/local_session.py
> +               data capture on the endpoint (Default value = None)
Thank you so much!

2021-02-26 18:26 UTC, akionakamura commented
@ChoiByungWook can you help me understand these build errors? Is there something I can do?

2021-02-27 00:42 UTC, ChoiByungWook commented
> @ChoiByungWook can you help me understand these build errors? Is there something I can do?

Not a problem on your end. We ran into some issues on our end.

2021-02-27 02:36 UTC, merged