feature: Allow users to send custom attributes to the model endpoint
aws/sagemaker-python-sdk pull request #2198
Opened 2021-03-09 19:44 UTC by keerthanvasist

*Description of changes:*

*Testing done:*
Unit tests

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-09 21:03 UTC, milah requested changes

2021-03-09 21:03 UTC, milah commented on tests/unit/test_clarify.py
> +        custom_attributes=custom_attributes
, at end (here and below)

2021-03-09 21:09 UTC, keerthanvasist commented on tests/unit/test_clarify.py
> +        custom_attributes=custom_attributes
Done

2021-03-10 01:05 UTC, milah submitted a review, later dismissed

2021-03-12 04:32 UTC, ChoiByungWook approved these changes

2021-03-13 01:33 UTC, ChoiByungWook commented
> ### AWS CodeBuild CI Report
> * CodeBuild project: sagemaker-python-sdk-notebook-tests
> * Commit ID: [2233602](https://github.com/aws/sagemaker-python-sdk/commit/22336028d0e8874b605060aeded1d3fbf26425f9)
> * Result: FAILED
> * [Build Logs](https://jr6hkjvk5d.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=6e9974ca-20c0-4682-985f-f9d60d1959a6%2Fbuild.log) (available for 30 days)
> 
> _Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)_

2021-03-15 19:41 UTC, merged