Update estimator.py
aws/sagemaker-python-sdk pull request #2466
Opened 2021-06-17 19:02 UTC by IvyBazan

*Description of changes:*
Update supported Hugging face versions

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [X] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [X] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-16 02:50 UTC, ahsan-z-khan requested changes

2021-07-16 02:50 UTC, ahsan-z-khan commented on src/sagemaker/huggingface/estimator.py
> +                ``pytorch_version`` is provided. The current supported version is ``2.4.1``.
It should be vice versa. TF is 2.4.1

2021-07-16 16:46 UTC, IvyBazan commented on src/sagemaker/huggingface/estimator.py
> +                ``pytorch_version`` is provided. The current supported version is ``2.4.1``.
This is an update to the TF version doc

2021-07-17 03:17 UTC, shreyapandit approved these changes

2021-07-18 00:59 UTC, ahsan-z-khan approved these changes

2021-07-18 01:00 UTC, merged