feature: add LambdaStep support for sagemaker pipelines
aws/sagemaker-python-sdk pull request #2544
Opened 2021-07-29 22:42 UTC by rohangujarathi

*Issue #, if available:*
AML-116688

*Description of changes:*
Added a new Lambda_helper class and boto3 wrappers to create, update, delete and invoke lambdas
Added relevant unit tests and integ tests
*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-30 15:35 UTC, staubhp approved these changes

2021-08-02 16:54 UTC, staubhp approved these changes

2021-08-02 19:27 UTC, ahsan-z-khan commented
@rohangujarathi 
There are some commits from Feb 16 and Feb 17. Please remove the commit on the PR. And clean it with only relevant ones.

2021-08-02 19:51 UTC, ahsan-z-khan requested changes

2021-08-02 19:51 UTC, ahsan-z-khan commented on src/sagemaker/lambda_helper.py
> +# Copyright 2019-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Please remove the years from the public PR as the new guideline.

2021-08-02 19:51 UTC, ahsan-z-khan commented on src/sagemaker/workflow/lambda_step.py
> +# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Delete year

2021-08-02 19:51 UTC, ahsan-z-khan commented on tests/unit/sagemaker/workflow/test_lambda_step.py
> +# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
delete year

2021-08-02 21:17 UTC, rohangujarathi commented
closing this PR in favour of https://github.com/aws/sagemaker-python-sdk/pull/2548

2021-08-02 21:17 UTC, closed without merging