feature: Add support for SageMaker lineage queries context
aws/sagemaker-python-sdk pull request #2830
Opened 2022-01-06 17:37 UTC by yzhu0

*Issue #, if available:*

*Description of changes:*
Add support for SageMaker lineage queries context
- Return Processing jobs in EndpointContext
- Return Trial Components in EndpointContext
- Return Pipeline Execution in ModelPackageGroup

*Testing done:*
Integration test
 tox -e py36 -- tests/integ/sagemaker/lineage/test_model_package_group_context.py -vv

`tests/integ/sagemaker/lineage/test_model_package_group_context.py::test_pipeline_execution_arn PASSED                                                                                                        [100%]`

 tox -e py36 -- tests/integ/sagemaker/lineage/test_endpoint_context.py -vv
`
collected 6 items
tests/integ/sagemaker/lineage/test_endpoint_context.py::test_model PASSED                                                                                                                                    [ 16%]
tests/integ/sagemaker/lineage/test_endpoint_context.py::test_dataset_artifacts PASSED                                                                                                                        [ 33%]
tests/integ/sagemaker/lineage/test_endpoint_context.py::test_training_job_arns PASSED                                                                                                                        [ 50%]
tests/integ/sagemaker/lineage/test_endpoint_context.py::test_processing_job_arns PASSED                                                                                                                      [ 66%]
tests/integ/sagemaker/lineage/test_endpoint_context.py::test_trial_components_arns PASSED                                                                                                                    [ 83%]
tests/integ/sagemaker/lineage/test_endpoint_context.py::test_pipeline_execution_arn PASSED                                                                                                                   [100%]
`

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-07 17:34 UTC, staubhp approved these changes

2022-01-07 18:41 UTC, staubhp approved these changes

2022-01-12 00:21 UTC, ahsan-z-khan approved these changes

2022-01-12 00:30 UTC, mufaddal-rohawala requested changes

2022-01-12 00:30 UTC, mufaddal-rohawala commented on src/sagemaker/lineage/context.py
> +    def processing_job_arns(
Please add unit tests for this.

2022-01-12 00:30 UTC, mufaddal-rohawala commented on src/sagemaker/lineage/context.py
> +    def trial_components_arns(
Please add unit tests for this.

2022-01-12 00:30 UTC, mufaddal-rohawala commented on src/sagemaker/lineage/context.py
> +class ModelPackageGroup(Context):
Please add unit tests for this.

2022-01-13 06:20 UTC, shreyapandit commented on src/sagemaker/lineage/context.py
> +        # return self.properties["PipelineExecutionArn"]
Is this needed? Please remove commented out code prior to merge.

2022-01-13 06:20 UTC, shreyapandit commented on src/sagemaker/lineage/query.py
>              filter_request["Types"] = list(
Was this a bug before?

2022-01-13 06:22 UTC, shreyapandit requested changes
Needs additional tests and other minor feedback to be addressed

2022-01-19 18:01 UTC, jeniyat approved these changes
looks good to me

2022-01-19 18:05 UTC, mufaddal-rohawala approved these changes

2022-01-19 20:52 UTC, yzhu0 commented
> Needs additional tests and other minor feedback to be addressed

addressed all

2022-01-19 21:08 UTC, shreyapandit approved these changes

2022-01-19 21:08 UTC, merged