feat: script mode support for estimator class
aws/sagemaker-python-sdk pull request #2834
Opened 2022-01-07 20:39 UTC by evakravi

*Issue #, if available:*

*Description of changes:*

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-11 15:06 UTC, JGuinegagne requested changes
Would you be able to add unit tests to verify that:
- `git_config` is also handled correctly and similarly b7 `DummyFramework` and `Estimator`
- `hyperparameters` are handled correctly (if not covered already)

2022-01-19 21:13 UTC, JGuinegagne reviewed
A few non-blocking comments/suggestions.

2022-01-19 21:13 UTC, JGuinegagne commented on src/sagemaker/estimator.py
> +        """Sets hyperparameters."""
Let's avoid repeating function name in docstring. How about:
```py
"""Escape the dict argument as JSON, update the private hyperparameter attribute."""
```

2022-01-19 21:13 UTC, JGuinegagne commented on src/sagemaker/model.py
> +            )
nit for readability, i would vote for:
```py
is_repack = self.source_dir and self.entry_point and not (self.key_prefix or self.git_config)
self._upload_code(deploy_key_prefix, repack=is_repack)
```

2022-01-19 21:38 UTC, evakravi commented on src/sagemaker/estimator.py
> +            kms_key = self.output_kms_key if code_bucket == output_bucket else None
No idea, this section was directly lifted from somewhere else in the code.

2022-01-19 23:33 UTC, JGuinegagne approved these changes

2022-01-19 23:35 UTC, JGuinegagne commented on src/sagemaker/estimator.py
> +            kms_key = self.output_kms_key if code_bucket == output_bucket else None
@shreyapandit @mufaddal-rohawala ?

2022-01-20 23:32 UTC, mufaddal-rohawala approved these changes

2022-01-21 00:00 UTC, shreyapandit commented on src/sagemaker/estimator.py
> +            kms_key = self.output_kms_key if code_bucket == output_bucket else None
will need to dive into this.

2022-01-21 00:22 UTC, shreyapandit approved these changes

2022-01-21 00:22 UTC, merged