fix: local mode deletion of temp files on job end
aws/sagemaker-python-sdk pull request #3017
Opened 2022-03-22 03:53 UTC by jmahlik

*Issue #, if available:*
closes [#2527](https://github.com/aws/sagemaker-python-sdk/issues/2647)

This is a clone of https://github.com/aws/sagemaker-python-sdk/pull/2644 but has allow commits from maintainers on so should be easier to merge. 

Description of changes:

Add try except around file cleanup in sagemaker.local.utils.copy_directory_structure. This was causing local mode to fail when docker (running as root) writes files to a mounted dir and the user does not have permission to remove the files.

The same pattern is followed [here](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/local/image.py#L956).

Testing done:

Add test for failed removal, behaves as expected.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-26 23:09 UTC, vikas0203 reviewed
/bot run all

2022-12-02 21:15 UTC, navinsoni requested changes
@jmahlik Thanks for your contribution. Can you please update your PR and resolve conflicts.

2022-12-06 14:06 UTC, jmahlik commented
> @jmahlik Thanks for your contribution. Can you please update your PR and resolve conflicts.

My hard disk failed recently so I have to set up a new vm. It might take a bit. Open to you editing or cherry picking this in the meantime if you'd like? It should be open. Been trying to get this merged since September 2021.

2022-12-14 04:20 UTC, jmahlik commented
> @jmahlik Thanks for your contribution. Can you please update your PR and resolve conflicts.

@navinsoni rebased

2022-12-15 21:09 UTC, navinsoni reviewed
/bot run all

2022-12-15 21:10 UTC, navinsoni approved these changes

2022-12-15 21:11 UTC, navinsoni commented
@jmahlik I have approved the PR. I will merge it as soon as all tests pass.

2022-12-15 22:44 UTC, navinsoni reviewed
/bot run all

2022-12-15 22:50 UTC, navinsoni commented
@jmahlik Can you please fix unit-tests. it's failing for flake8 and black. 
You can test it locally by running `tox -e flake8,pylint,docstyle,black-check,twine`

2022-12-15 23:07 UTC, jmahlik commented
Yes will do. I ran black and it tried to re-format the entire repo so something must be off locally.

2022-12-15 23:22 UTC, jmahlik commented
Ok should be fixed now. I forgot to push this. 

```patch
diff --git a/tests/unit/sagemaker/local/test_local_utils.py b/tests/unit/sagemaker/local/test_local_utils.py
index ab8d556d..59caa5f0 100644
--- a/tests/unit/sagemaker/local/test_local_utils.py
+++ b/tests/unit/sagemaker/local/test_local_utils.py
@@ -165,6 +165,7 @@ def test_get_using_dot_notation_key_error():

 def test_get_using_dot_notation_index_error():
     with pytest.raises(ValueError):
+        sagemaker.local.utils.get_using_dot_notation({"foo": ["bar"]}, "foo[1]")
```

2022-12-16 01:51 UTC, jmahlik commented
Docs looks like it fails fetching jumpstart tables from s3

2022-12-19 18:32 UTC, navinsoni reviewed
/bot run slow-tests

2023-01-11 18:30 UTC, jmahlik commented
@navinsoni looks like some unrelated tests are falling on this one. Let me know if you'd like me to rebase or anything.

2023-01-18 16:50 UTC, claytonparnell reviewed
/bot run slow-tests

2023-01-18 16:58 UTC, claytonparnell commented
@jmahlik - looks like just some intermittent failures that we're working on resolving, should pass on retry. I'll get those passing so we can merge this in. Thanks again for contributing!

2023-02-08 20:02 UTC, trajanikant reviewed
/bot run notebook-tests, slow-tests

2023-02-17 16:18 UTC, jmahlik commented
I can rebase if needed. Whenever the flakey tests start passing, it'd be nice to fix this.  It is kind of annoying supporting 200+ sagemaker users who keep running in to this. I've been trying since 2021. Sorry to say but I'll close this and refer them to support if we can't figure this out. Kind of hard to contribute here, maybe we can do a tad better. Seems to have started when the jumpstart tests went in.

2023-02-22 02:49 UTC, merged

2023-02-22 02:50 UTC, claytonparnell commented
Apologies @jmahlik it has been merged. We've been trying to prioritize fixing the PR tests, will be resolved soon.