change: update modelparallel config validation
aws/sagemaker-python-sdk pull request #3048
Opened 2022-04-05 19:49 UTC by karakusc

*Issue #, if available:*

*Description of changes:* Updating the config validation for the modelparallel library, based on the latest release.

*Testing done:* Ran GPT-2 example script with the updated SageMaker Python SDK.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-07 18:41 UTC, ahsan-z-khan requested changes
Most of the unit tests failed. 

```
ERROR:  flake8: parallel child exit code 1
ERROR: pylint: parallel child exit code 1
ERROR:  docstyle: parallel child exit code 1
ERROR:   black-check: parallel child exit code 1
```

Please test it locally before pushing new changes. Also consider configuring pre-commit hooks mentioned in the README.

2022-04-22 18:26 UTC, mufaddal-rohawala requested changes

2022-04-22 18:26 UTC, mufaddal-rohawala commented on src/sagemaker/mp_config.py
> +    def get_value(self):
Can we use python properties here instead of getter/setter ?

2022-04-22 18:26 UTC, mufaddal-rohawala commented on src/sagemaker/mp_config.py
> +    def _set_value(self, input_value):
Can we use python properties here instead of getter/setter ?
Also this func is too long, can we make this more modular?

2022-04-22 18:26 UTC, mufaddal-rohawala commented on src/sagemaker/mp_config.py
> +    py_sdk = True
nit: I would like to see if we can deduct this is in a more reliable manner?

2022-04-22 18:26 UTC, mufaddal-rohawala commented on src/sagemaker/mp_config.py
> +    def __init__(self, config):
This init func is too long, can we make this more modular?

2022-04-22 18:26 UTC, mufaddal-rohawala commented on setup.py
> +    package_data={"sagemaker": ["mp_config.yaml"]},
Can we add this to [MANIFEST.in](https://github.com/aws/sagemaker-python-sdk/blob/master/MANIFEST.in) file rather?

2023-02-13 19:03 UTC, mufaddal-rohawala reviewed
/bot run all

2023-02-21 22:00 UTC, mufaddal-rohawala commented
Talked to @karakusc , closing this. Will reopen new PR if needed.

2023-02-21 22:00 UTC, closed without merging