deprecate: Remove deprecated argument s3_data_distribution_type
aws/sagemaker-python-sdk pull request #3064
Opened 2022-04-12 22:49 UTC by keerthanvasist

*Description of changes:*
Remove deprecated argument s3_data_distribution_type. We have already given enough warning time for customers to stop using this parameter. Besides, the deprecation warning has removed the `DataConfig` parameter from the docs. In order to resolve that, and complete the deprecation, we are removing the parameter `s3_data_distribution_type`.

*Testing done:*
Unit tests passed. 

## Merge Checklist

#### General

- [x ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x ] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-20 20:03 UTC, ahsan-z-khan requested changes
Unit tests are failing on formatting and `flake8`. Please run the tests locally before committing. Also consider having the pre-push hook mentioned in the guide.

2022-05-02 01:44 UTC, mufaddal-rohawala approved these changes

2022-05-03 17:06 UTC, shreyapandit approved these changes

2022-05-03 17:18 UTC, ahsan-z-khan approved these changes

2022-05-03 17:20 UTC, navinsoni approved these changes

2022-05-03 18:35 UTC, merged