feat: Add target_model to support multi-model endpoints
aws/sagemaker-python-sdk pull request #3215
Opened 2022-07-06 21:11 UTC by keerthanvasist

*Issue #, if available:*
Add `target_model` to support multi-model endpoints in Clarify processing jobs. 

*Testing done:*
Added unit tests. 

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-06 21:52 UTC, keerthanvasist commented on src/sagemaker/clarify.py
> +        target_model=None,
No

2022-07-06 23:38 UTC, goswamig commented on src/sagemaker/clarify.py
> +            more information about multi-model endpoints
I think you want to add link of multi-model endpoints.

2022-07-06 23:39 UTC, goswamig requested changes
I think you want to add link of multi-model endpoints.

2022-07-06 23:47 UTC, goswamig approved these changes
LGTM

2022-07-07 17:21 UTC, Satish615 approved these changes

2022-07-08 21:39 UTC, navinsoni approved these changes

2022-07-11 22:32 UTC, mufaddal-rohawala approved these changes

2022-07-11 22:33 UTC, merged