Using logger instead of print
aws/sagemaker-python-sdk pull request #3219
Opened 2022-07-08 12:36 UTC by Guillem96

*Issue #, if available:*

*Description of changes:*

Instead of using `print` function use the `logger`.

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-25 23:59 UTC, vikas0203 reviewed
/bot run all

2022-10-26 00:00 UTC, vikas0203 approved these changes

2022-11-24 01:27 UTC, mufaddal-rohawala requested changes
tests are failing can you check units?

2022-11-24 01:27 UTC, mufaddal-rohawala commented on src/sagemaker/processing.py
>          # Print the job name and the user's inputs and outputs as lists of dictionaries.
Can we update the comment as well?

2023-02-01 23:27 UTC, mufaddal-rohawala commented
Closing PR as there are no updates for a long time.

2023-02-01 23:27 UTC, closed without merging