feat: added ANALYSIS_CONFIG_SCHEMA_V1_0 in clarify
aws/sagemaker-python-sdk pull request #3325
Opened 2022-08-23 14:04 UTC by dosatos

*Issue #, if available:*

*Description of changes:*
When containers run, such schema validation is applied anyways. 
So added `ANALYSIS_CONFIG_SCHEMA_V1_0` to shorten feedback.

I also, added a flag for users to skip early validation. So they are not blocked in case we add a new feature in containers,  but cannot manage deploying the update in SDK on time.

*Testing done:*
- Added unit tests for 
- Used Schema containers use on the backend side.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-24 18:53 UTC, larroy reviewed
I would leave the s3 validation for a separate change and get further feedback, and do the basic validation first. I think otherwise is good

2022-08-24 19:42 UTC, dosatos commented
> I would leave the s3 validation for a separate change and get further feedback, and do the basic validation first. I think otherwise is good

Got it, removed for now.

2022-08-24 19:51 UTC, larroy approved these changes
LGTM

2022-08-24 19:52 UTC, larroy commented on src/sagemaker/clarify.py
> +        skip_early_validation: bool = False,
please document skip_early_validation

2022-08-25 16:10 UTC, mufaddal-rohawala reviewed
/bot run slow-tests

2022-08-26 22:59 UTC, keerthanvasist requested changes
Did we have a discussion within the team? I believe this is arranged for next week. Please wait for approval from the team before merging this.

2022-08-29 20:06 UTC, dosatos commented
> Did we have a discussion within the team? I believe this is arranged for next week. Please wait for approval from the team before merging this.

As discussed today with the team, let's proceed with the change

2022-08-31 19:20 UTC, pinaraws approved these changes

2022-08-31 20:02 UTC, keerthanvasist approved these changes

2022-09-02 19:18 UTC, BasilBeirouti commented
I have resolved merge conflicts in `clarify.py` and we need to wait for the tests to run again

2022-09-05 09:26 UTC, dosatos commented
not sure why, but the conflicts kept popping - I cleaned it again and re-based it from scratch (note: had to overwrite the commits, though). waiting for build stages to finish

2022-09-22 22:27 UTC, merged