fix: StepTypeEnum couldn't be instantiated correctly
aws/sagemaker-python-sdk pull request #3345
Opened 2022-09-02 21:47 UTC by navaj0

*Issue #, if available:*

#3272

*Description of changes:*

For example, StepTypeEnum('Processing') leads to StepTypeEnum.CONDITION because the value arg is not put in the right position of the DefaultEnumMeta.__call__ method

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-06 20:03 UTC, nmadan approved these changes

2022-09-06 21:08 UTC, qidewenwhen approved these changes

2022-12-02 21:10 UTC, navinsoni approved these changes

2022-12-15 22:48 UTC, navinsoni requested changes
@navaj0 Can you please fix unit-tests and resolve conflicts

2023-03-01 05:10 UTC, mufaddal-rohawala commented
@navaj0 Can you please fix unit-tests and resolve conflicts

2023-03-09 21:12 UTC, closed without merging