feature: Added transform with monitoring pipeline step in transformer
aws/sagemaker-python-sdk pull request #3438
Opened 2022-10-26 05:58 UTC by keshav-chandak

*Issue #, if available:*

*Description of changes:*

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-26 06:24 UTC, adeel-zafar requested changes

2022-10-26 06:24 UTC, adeel-zafar commented on src/sagemaker/transformer.py
> +        instead, it will create a SageMaker Pipeline and execute it.g331
Typo, `execute it.g331`

2022-10-26 06:49 UTC, keshav-chandak commented on src/sagemaker/transformer.py
> +        instead, it will create a SageMaker Pipeline and execute it.g331
fixed

2022-10-31 13:05 UTC, adeel-zafar approved these changes
LGTM

2022-11-02 00:09 UTC, jerrypeng7773 approved these changes

2022-11-16 00:46 UTC, mufaddal-rohawala reviewed
/bot run slow-tests

2022-11-16 01:55 UTC, knikure approved these changes

2022-12-02 22:11 UTC, merged

2023-01-10 11:15 UTC, rahven14 commented on src/sagemaker/transformer.py
> +        from sagemaker.workflow.pipeline import Pipeline
Move import to top of the file

2023-01-10 11:18 UTC, rahven14 commented on tests/integ/test_transformer.py
> +        model_name=xgb_model.name,
this line has the potential to throw an exception, if xgb_model.name is not accessible. So please have a check like,
model_name = xgb_model.name if xgb_model else None or something to fill in the else case.

2023-01-10 11:21 UTC, rahven14 commented on tests/integ/test_transformer.py
> +    xgb_model.deploy(_INSTANCE_COUNT, _INSTANCE_TYPE)
are they private variables defined somewhere, not able to find it.