Torchrun gpu support documentation change
aws/sagemaker-python-sdk pull request #3698
Opened 2023-03-07 00:28 UTC by yl-to

*Issue #, if available:*

*Description of changes:*

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-07 22:27 UTC, mchoi8739 commented on doc/frameworks/pytorch/using_pytorch.rst
> +  The SageMaker PyTorch estimator can operates both ``mpirun`` and ``torchrun`` in the backend for distributed training.
We should add an example code line to show how to specify these backend options in the config.

2023-03-07 22:32 UTC, mchoi8739 commented on doc/frameworks/pytorch/using_pytorch.rst
> +  in the AWS Deep Learning Containers for PyTorch Neuron starting v1.11.0 and other gpu instances starting v1.13.1.
I think this update is not adequate, because this section is specifically about PT Neuron container on Trn1

2023-03-07 23:32 UTC, mchoi8739 requested changes

2023-03-07 23:32 UTC, mchoi8739 commented on src/sagemaker/pytorch/estimator.py
> +                    This is available for general distributed training on
```suggestion
                    
                    This is available for general distributed training on 
```

2023-03-07 23:32 UTC, mchoi8739 commented on doc/frameworks/pytorch/using_pytorch.rst
> +    see `torchrun (Elastic Launch) <https://pytorch.org/docs/stable/elastic/run.html>_` in *the
```suggestion
    see `torchrun (Elastic Launch) <https://pytorch.org/docs/stable/elastic/run.html>`_ in *the
```

2023-03-08 01:30 UTC, mufaddal-rohawala approved these changes

2023-03-08 22:13 UTC, navinsoni reviewed
/bot run all

2023-03-08 23:47 UTC, merged