feature: Enable default role for Spark processors
aws/sagemaker-python-sdk pull request #3801
Opened 2023-04-19 19:26 UTC by ivan-khvostishkov

*Issue #, if available:*
N/A

*Description of changes:*
This patch enables setting [default values](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-sagemaker-python-sdk-default-values-parameters/) (`role` parameter) for Spark processors.

*Testing done:*
Yes

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-08 18:20 UTC, claytonparnell requested changes

2023-05-08 18:20 UTC, claytonparnell commented on src/sagemaker/spark/processing.py
> +        role: str = None,
Can you update docstring to show that these now default to None, and a quick statement of what happens when None? See `dependency_location` docstring on L781 for example

2023-05-09 15:39 UTC, ivan-khvostishkov commented on src/sagemaker/spark/processing.py
> +        role: str = None,
Done.

2023-05-18 20:02 UTC, knikure reviewed
/bot run notebook-tests

2023-05-19 01:19 UTC, knikure approved these changes

2023-05-19 01:20 UTC, merged