documentation: add description for parameters in TransformInput
aws/sagemaker-python-sdk pull request #3817
Opened 2023-04-26 19:20 UTC by mwfongAWS

*Issue #, if available:* 
https://t.corp.amazon.com/V754050092

*Description of changes:*
Add description for parameters in TransformInput()

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-26 20:50 UTC, trajanikant reviewed
/bot run all

2023-05-05 20:56 UTC, knikure reviewed
/bot run all

2023-05-09 23:02 UTC, mwfongAWS commented
Sorry I had no idea what I was doing before and I got distracted with other projects. I'm hoping this one works out! I made the changes on my laptop and ran the tests and they succeeded after I ran 
tox -e black-check,flake8,pylint,docstyle,sphinx,doc8 —parallel all
then 
tox -e black-format

2023-05-11 16:14 UTC, knikure reviewed
/bot run all

2023-05-11 21:49 UTC, mchoi8739 requested changes

2023-05-11 21:49 UTC, mchoi8739 commented on src/sagemaker/inputs.py
> +        data_type (str): elastic inference accelerator type.
Question, 

the arg name is "data_type" but the description is "the type of an elastic inference accelerator", which is not a data type?

2023-05-11 21:49 UTC, mchoi8739 commented on src/sagemaker/inputs.py
> +            (default: ``{'InvocationsTimeoutInSeconds'=600,'InvocationsMaxRetries'=3}``)
Is this a correct form? I think dict should be in { 'key': 'value' } pair format.

2023-05-11 21:49 UTC, mchoi8739 commented on src/sagemaker/inputs.py
> +            data capture for use with Amazon SageMaker Model Monitoring.
What is "batch transform job data capture"? It seems that more explanation is needed breaking this term down.

2023-05-11 22:11 UTC, mchoi8739 commented on src/sagemaker/inputs.py
> +        data_type (str): elastic inference accelerator type.
Actually should it be "The data type for batch transform job"?

2023-05-11 22:14 UTC, mchoi8739 commented on src/sagemaker/inputs.py
> +        data_type (str): The data type for an elastic inference accelerator.
Actually should it be "The data type for a batch transform job"? "an elastic inference accelerator" is only a device.

2023-05-11 22:35 UTC, mchoi8739 requested changes

2023-05-11 22:35 UTC, mchoi8739 commented on src/sagemaker/inputs.py
>      """Create a class containing all the parameters.
```suggestion
    """Creates a class containing parameters for configuring input data for a batch tramsform job.
```

2023-05-11 22:35 UTC, mchoi8739 commented on src/sagemaker/inputs.py
> +        batch_data_capture_config (dict): Specifies configuration related to batch transform job
```suggestion
        batch_data_capture_config (An object of `BatchDataCaptureConfig <https://sagemaker.readthedocs.io/en/stable/api/utility/inputs.html#sagemaker.inputs.BatchDataCaptureConfig>`_): 
        Specifies configuration to capture data from a batch transform job
```

2023-05-11 22:35 UTC, mchoi8739 commented on src/sagemaker/inputs.py
> +            data capture for use with Amazon SageMaker Model Monitoring. For more information about
```suggestion
            for use with Amazon SageMaker Model Monitoring. For more information,
```

2023-05-11 22:35 UTC, mchoi8739 commented on src/sagemaker/inputs.py
> +            batch transform job data capture, see `Capture data from batch transform job
```suggestion
            see `Capture data from batch transform job
```

2023-05-11 23:04 UTC, mchoi8739 approved these changes

2023-05-12 00:09 UTC, knikure reviewed
/bot run all

2023-05-12 16:24 UTC, mchoi8739 commented on src/sagemaker/inputs.py
> +        <https://sagemaker.readthedocs.io/en/stable/api/utility/inputs.html#sagemaker.inputs.BatchDataCaptureConfig>`_)
```suggestion
            <https://sagemaker.readthedocs.io/en/stable/api/utility/inputs.html#sagemaker.inputs.BatchDataCaptureConfig>`_)
```

2023-05-13 00:18 UTC, mchoi8739 commented on src/sagemaker/inputs.py
> +            <https://sagemaker.readthedocs.io/en/stable/api/utility/inputs.html#sagemaker.inputs.BatchDataCaptureConfig>`_)
```suggestion
            <https://sagemaker.readthedocs.io/en/stable/api/utility/inputs.html#sagemaker.inputs.BatchDataCaptureConfig>`_):
```

2023-05-16 18:44 UTC, knikure reviewed
/bot run all

2023-05-16 19:32 UTC, knikure approved these changes
/bot run all

2023-05-16 19:33 UTC, knikure reviewed
/bot run all

2023-05-16 20:55 UTC, merged