Add features_to_explain to shap config
aws/sagemaker-python-sdk pull request #3951
Opened 2023-06-22 07:02 UTC by oyangz

*Issue #, if available:* https://issues.amazon.com/issues/RAI-5317

*Description of changes:* Add features_to_explain to Clarify SHAPConfig

*Testing done:* tox tests passed

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-23 17:46 UTC, mufaddal-rohawala requested changes

2023-06-23 17:46 UTC, mufaddal-rohawala commented on src/sagemaker/clarify.py
> +            raise ValueError(
please add this in method docstring

2023-06-23 18:02 UTC, malhotra18 approved these changes
LGTM!

2023-06-23 19:46 UTC, oyangz commented on src/sagemaker/clarify.py
> +            raise ValueError(
Sure, will do.

2023-06-23 22:39 UTC, oyangz commented on src/sagemaker/clarify.py
> +            raise ValueError(
Added in latest commit.

2023-07-06 18:12 UTC, mufaddal-rohawala approved these changes

2023-07-06 18:54 UTC, mufaddal-rohawala commented
Bypassing notebook tests (due to a known timeout issue), the timed out notebooks have been verified successfully atleast once in subsequent iterations.

2023-07-06 18:54 UTC, merged