feat: jumpstart model artifact instance type variants
aws/sagemaker-python-sdk pull request #4172
Opened 2023-10-06 16:31 UTC by evakravi

*Issue #, if available:*

*Description of changes:*
JumpStart plans on introducing models that may have different model artifacts depending on the instance type chosen. This will require new metadata, and new SDK code for consuming this metadata.

*Testing done:*
Unit tests added

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-06 17:35 UTC, whittech1 commented on src/sagemaker/jumpstart/types.py
> +            instance_type=instance_type, property_name="prepacked_artifact_key"
nit: should the property name include `s3`?

2023-10-06 17:35 UTC, whittech1 commented on src/sagemaker/jumpstart/artifacts/model_uris.py
> +            and getattr(model_specs, "hosting_instance_type_variants", None) is not None
Isn't the name of the property `hosting_custom_instance_type_variants` in the MH PR?

2023-10-06 17:35 UTC, whittech1 commented on src/sagemaker/jumpstart/artifacts/model_uris.py
> +            instance_specific_prepacked_hosting_artifact_key
I think this logic can break if there is an instance-specific normal artifact but a default prepacked artifact. Previously, just the presence of default prepacked artifact would have indicated a need to prepack.

To be exact, we need to change the execution flow based on whether `model_specs` is prepacked or not. Quick-and-dirty approach would be something like:

```
is_prepacked = model_specs.hosting_use_script_uri or default_prepacked_hosting_artifact_key
if is_prepacked:
    return instance_specific_prepack_key or default_prepacked_hosting_artifact_key
else:
    return instance_specific_key or default_hosting_artifact_key
```

2023-10-09 13:32 UTC, JGuinegagne requested changes
Could you add specific unit tests for (a) `sagemaker/model_uri` and (b) `ssagemaker/jumpstart/artifacts/model_uris` please?

I know you are implicitely testing through `JumpStartModel` and `JumpStartEstimator`, but we should guard ourselves against specific logic introduced in these classes and test the utilities directly as well.

2023-10-09 13:32 UTC, JGuinegagne commented on src/sagemaker/jumpstart/artifacts/model_uris.py
> +            model artifacts specific for the instance type. (Default: None).
`Optional. The ML compute instance type for the specified scope. (Default: None).`

2023-10-09 13:32 UTC, JGuinegagne commented on src/sagemaker/jumpstart/artifacts/model_uris.py
>          )
The hosting artifact retrieval logic is quite complex and the implementation is too linear IMO. Could you break it down into utilities that you can unit test separately.

E.g.
```py
if model_scope == JumpStartScriptScope.INFERENCE:
  if is_model_prepacked(...):
    return artifacts.retrieve_instance_specific_hosting_prepack_key(...)
  else:
    return artifacts.retrieve_instance_specific_hosting_artifact_key(...)
elif model_scope === JumpStartScriptScope.TRAINING:
  return artifacts.retrieve_instance_specific_training_artifact_key(...)
```

Then delegate to each utility method the task of handling whether (a) an instance was passed, (b) if (a) is true, whether it maps + add unit tests for each case.

2023-10-09 13:32 UTC, JGuinegagne commented on src/sagemaker/model_uris.py
> +            model artifacts specific for the instance type. (Default: None).
same comment here.

2023-10-09 13:32 UTC, JGuinegagne commented on tests/unit/sagemaker/jumpstart/constants.py
> +                    "properties": {"environment_variables": {"TENSOR_PARALLEL_DEGREE": "4"}}
could you add a test with an instance specific `prepacked_artifact_key` as well please?

As in not just instance family variant please.

Same for training case please

2023-10-09 17:09 UTC, JGuinegagne reviewed
Could you update the docstring as well please?

2023-10-16 16:39 UTC, whittech1 approved these changes

2023-10-16 18:44 UTC, evakravi reviewed
/bot run slow-tests

2023-10-17 14:03 UTC, evakravi reviewed
/bot run pr

2023-10-17 20:31 UTC, knikure commented
@evakravi Can you resolve conflicts on this PR?

2023-10-18 14:28 UTC, merged